// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {card} from '../models';

export function CalculateHandValue(arg1:Array<card.Card>,arg2:boolean):Promise<number>;

export function StartGame():Promise<void>;

export function StopGame():Promise<void>;
