// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {blackjack} from '../models';

export function DefaultConfig():Promise<blackjack.BlackjackConfig>;

export function NewDefaultGame():Promise<blackjack.BlackjackGame>;
