// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {blackjack} from '../models';
import {card} from '../models';

export function CalculateBestHandValue(arg1:blackjack.BlackjackGame,arg2:Array<card.Card>):Promise<number>;

export function ClearHands(arg1:blackjack.BlackjackGame):Promise<void>;

export function DefaultConfig():Promise<blackjack.BlackjackConfig>;

export function NewDefaultGame():Promise<blackjack.BlackjackGame>;
