// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateHandValue(arg1, arg2) {
  return window['go']['blackjack']['BlackjackGame']['CalculateHandValue'](arg1, arg2);
}

export function StartGame() {
  return window['go']['blackjack']['BlackjackGame']['StartGame']();
}

export function StopGame() {
  return window['go']['blackjack']['BlackjackGame']['StopGame']();
}
