// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateBestHandValue(arg1, arg2) {
  return window['go']['blackjack']['BlackjackLib']['CalculateBestHandValue'](arg1, arg2);
}

export function ClearHands(arg1) {
  return window['go']['blackjack']['BlackjackLib']['ClearHands'](arg1);
}

export function DefaultConfig() {
  return window['go']['blackjack']['BlackjackLib']['DefaultConfig']();
}

export function NewDefaultGame() {
  return window['go']['blackjack']['BlackjackLib']['NewDefaultGame']();
}
