// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultConfig() {
  return window['go']['blackjack']['BlackjackLib']['DefaultConfig']();
}

export function NewDefaultGame() {
  return window['go']['blackjack']['BlackjackLib']['NewDefaultGame']();
}
