// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CardValueToDisplayString(arg1) {
  return window['go']['card']['CardLib']['CardValueToDisplayString'](arg1);
}

export function CardValueToWord(arg1) {
  return window['go']['card']['CardLib']['CardValueToWord'](arg1);
}

export function MakeRandomCard() {
  return window['go']['card']['CardLib']['MakeRandomCard']();
}

export function NewStandardDeck() {
  return window['go']['card']['CardLib']['NewStandardDeck']();
}
