// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CardValueToDisplayString(arg1) {
  return window['go']['main']['App']['CardValueToDisplayString'](arg1);
}

export function CardValueToWord(arg1) {
  return window['go']['main']['App']['CardValueToWord'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MakeRandomCard() {
  return window['go']['main']['App']['MakeRandomCard']();
}

export function NewStandardDeck() {
  return window['go']['main']['App']['NewStandardDeck']();
}
