// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CardValueToDisplayString(arg1:number):Promise<string>;

export function CardValueToWord(arg1:number):Promise<string>;

export function MakeRandomCard():Promise<main.Card>;

export function NewStandardDeck():Promise<main.Deck>;
